"""Shared constants for procedural_buildings."""

# 3D axes
NUM_AXES = 3
AXIS_X = 0
AXIS_Y = 1
AXIS_Z = 2

# OBJ precision
OBJ_COORD_PRECISION = 6
VERTEX_FMT_PRECISION = 5
COLOUR_FMT_PRECISION = 4
PRIORITY_FMT_PRECISION = 5

# Grammar
DEFAULT_RULE_PRIORITY = 1.0
MAX_RULES = 10000
MAX_TOSTRING_DEPTH = 50

# Defaults
DEFAULT_SEPARATION = 10.0
DEFAULT_SCOPE_SIZE = [10, 10, 10]
NUM_SCOPE_COORDS = 6

# Box splitting
MAX_CONSECUTIVE_FAILURES = 6

# Random op graph generation
LEAF_PROBABILITY = 0.5
MIN_RELATIVE_SIZE = 20
MAX_RELATIVE_SIZE = 100

# Speed test
SPEEDTEST_REPEATS = 5
NUM_PRIMS_SCALE_FACTOR = 2
SPEEDTEST_SCOPE_SIZE = 1000
